name: CI Build / Merge

on:
  push:
    branches:
      - feature/**  # Pas de guillemets ici
  pull_request:
    branches:
      - master

jobs:
  build_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v3  # Version plus récente

    - name: Paramétrer PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Installer les dépendances composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install

    - name: Paramétrer Node.js
      uses: actions/setup-node@v3  # Version plus récente
      with:
        node-version: '20' 

    - name: Installer les dépendances npm
      run: npm install

    - name: Build Tailwind CSS
      run: npx tailwindcss -o public/css/tailwind.css

    - name: Lancer PHP Lint
      run: find . -name "*.php" -exec php -l {} \;

    - name: Commit si succès
      run: |
        git config --global user.name "GreenScoreWebPlugin"
        git config --global user.email "greenscore.plugin@gmail.com"
        git add .
        git commit -m "Commit automatique réussi" || echo "No changes to commit"

    - name: Merge vers master
      run: |
        git checkout master
        git pull origin master
        git merge ${{ github.head_ref }} --no-ff -m "Merge la branche dans master"
        git push origin master

    - name: Créer une erreur si fail
      if: failure()
      run: |
        echo "Build failed. Exiting."
        exit 1
